baseurl = "https://tensor.group"
defaultContentLanguage = "en"
disableRSS = true
enableRobotsTXT = true
languageCode = "en-us"
theme = "dimension"
title = "Tensor Group"
[languages.en]
languageName = "English"
title = "Tensor Group"
weight = 1
[params]
copyright = "Tensor Group"
description = "Helping you achieve your highest business and personal value through skilled consulting."
#logo = "fa-diamond"
# logoimage in /static at least 86*86 pixels
logoimage = "/images/tg-white-orange-logo-only.png"
title = "Tensor Group"
